### ISSUE TITLE
runfv3 run-native cannot parse diag_table overlay in fv3config.yml

### ISSUE THREAD

**Issue by AnnaKwa** [VulcanClimateModeling/fv3net#1098]
After some updates to the config preparation in https://github.com/VulcanClimateModeling/fv3net/pull/1051, I've run into issues in local prognostic runs  when reading in an `fv3config.yml` with a diag_table overlay entry. @oliverwm1 

Can be replicated in the prognostic run dev environment with
```
# this is an up to date version of an fv3config.yml after the diag table change
gsutil cp gs://vcm-ml-scratch/test-end-to-end-integration/integration-test-fd43a7fe5cb1/prognostic_run/fv3config.yml .
runfv3 run-native fv3config.yml rundir sklearn_runfile.py 
```

Results in
```
yq: Error running jq: TypeError: Object of type 'bytes' is not JSON serializable.
parse error: Unfinished JSON term at EOF at line 1, column 44128
```
I think it might be the formatting of the `base_time` key in the diag_table.

**Comment by oliverwm1** [comment]
Thanks for making the issue, I'll look into it.

**Comment by oliverwm1** [comment]
Thanks, yeah you're right that is the issue. We should add a test that calls `runfv3 run-native`.

Potential solutions:

1. get the "layout" in runfv3 using something other than yq. Downside... still can't use yq or jq to parse complete "fv3config.yml" objects.
2. change fv3config so that the diag table base time gets serialized in some JSON-readable format. E.g. could use the FV3 standard "current_date" format (a list of 6 ints for year, month, day, hour, minute, second). Would be a bit unpleasant to have to implement something like this.

**Comment by oliverwm1** [comment]
Thinking about this a little more, it is odd that it happens for `runfv3 run-native` but not `runfv3 append-segment` since they both end up calling the `runSegment` function.
